
---
- name: activity 2 - install php
  become: yes
  hosts: webservers
  tasks:
    - name: Print purpose
      ansible.builtin.debug:
        var: purpose

    - name: Fail on unsupported operating systems
      ansible.builtin.fail:
        msg: "This playbook will work on Debian and RedHat only"
      when: ansible_facts["os_family"] != "Debian" and ansible_facts["os_family"] != "RedHat"

    - name: Install Apache
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ all_packages }}"

    - name: Create info.php
      ansible.builtin.copy:
        content: '<?php phpinfo(); ?>'
        dest: /var/www/html/info.php

    - name: Ensure httpd is running
      ansible.builtin.service:
        name: "{{ package_name }}"
        enabled: yes
        state: started
